import React, { FC, ReactElement } from "react";
import { View, StyleSheet, Text } from "react-native";

interface HomeProps {}

export const Home: FC<HomeProps> = (): ReactElement => {
  return (
    <View style={styles.container}>
      <Text>Expo template generated by expo-native-create</Text>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
});
